### ISSUE TITLE
Issue with unity build

### ISSUE THREAD

**Issue by Siavash149** [myketstore/myket-billing-unity-sample#1]
سلام وقت بخیر
هنگام بیلد انردوید روی یونیتی این خطا رو بهم میده:
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':launcher:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':launcher:debugRuntimeClasspath'.
   > Could not resolve com.github.myketstore:myket-billing-unity:1.1.
     Required by:
         project :launcher > project :unityLibrary
      > Could not resolve com.github.myketstore:myket-billing-unity:1.1.
         > Could not get resource 'https://jitpack.io/com/github/myketstore/myket-billing-unity/1.1/myket-billing-unity-1.1.pom'.
            > Could not GET 'https://jitpack.io/com/github/myketstore/myket-billing-unity/1.1/myket-billing-unity-1.1.pom'.
               > The server may not support the client's requested TLS protocol versions: (TLSv1.2). You may need to configure the client to allow other protocols to be used. See: https://docs.gradle.org/6.9/userguide/build_environment.html#gradle_system_properties
                  > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
      > Could not resolve com.github.myketstore:myket-billing-unity:1.1.
         > Could not get resource 'https://jcenter.bintray.com/com/github/myketstore/myket-billing-unity/1.1/myket-billing-unity-1.1.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/github/myketstore/myket-billing-unity/1.1/myket-billing-unity-1.1.pom'.
               > The server may not support the client's requested TLS protocol versions: (TLSv1.2). You may need to configure the client to allow other protocols to be used. See: https://docs.gradle.org/6.9/userguide/build_environment.html#gradle_system_properties
                  > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
      > Could not resolve com.github.myketstore:myket-billing-unity:1.1.
         > Could not get resource 'https://jitpack.io/com/github/myketstore/myket-billing-unity/1.1/myket-billing-unity-1.1.pom'.
            > Could not GET 'https://jitpack.io/com/github/myketstore/myket-billing-unity/1.1/myket-billing-unity-1.1.pom'.
               > The server may not support the client's requested TLS protocol versions: (TLSv1.2). You may need to configure the client to allow other protocols to be used. See: https://docs.gradle.org/6.9/userguide/build_environment.html#gradle_system_properties
                  > sun.security.validator.ValidatorException: 
![Base](https://github.com/myketstore/myket-billing-unity-sample/assets/145572696/d70e9000-cfad-4860-b5b0-b1196f3b8100)
![Launcher](https://github.com/myketstore/myket-billing-unity-sample/assets/145572696/6170192e-48e1-4173-a7da-e3a51cb70797)
![Main](https://github.com/myketstore/myket-billing-unity-sample/assets/145572696/bf356770-ac78-4bce-8559-f765b5e7c16f)
PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

- از وی پی ان خوب استفاده می کنم (بیلد بقیه مارکت ها مشکلی نداره)
- فایل های template پروژه رو اتچ کردم که ببینید
 ممنون میشم راهنمایی کنید

**Comment by hmalekdev** [comment]
منم دقیقا همین مشکل رو دارم

**Comment by hmalekdev** [comment]
توی فایل SettingsTemplate این خط کد رو اضافه کنین مشکل حل میشه

maven { url 'https://jitpack.io' }
